name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Ajout de cette section pour donner les permissions
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit hash
        id: get_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Inject version into files
        run: |
          VERSION=${{ steps.get_hash.outputs.hash }}
          echo "Injecting version: $VERSION"
          # Le chemin est maintenant 'index.html' car l'action s'exécute à la racine du dépôt (le dossier 'bib')
          sed -i "s/__VERSION__/$VERSION/g" index.html sw.js
          echo "--- Content of index.html after sed ---"
          cat index.html
          echo "---------------------------------------"
          echo "--- Content of sw.js after sed ---"
          cat sw.js
          echo "---------------------------------------"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # La branche de déploiement
          # Le dossier à déployer est la racine du dépôt, représentée par '.'
          folder: .
          clean: true # Nettoie la branche de destination avant le déploiement
